apiVersion: v1
kind: Service
metadata:
  name: pingfederate-admin-nlb
  namespace: pfapps
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:767397705347:certificate/68784691-4ca0-4ef2-bdf7-d127e7737cbd
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-2016-08"
spec:
  ports:
  - name: https
    port: 443
    targetPort: 9999
    protocol: TCP
  type: LoadBalancer
  selector:
    role: pingfederate-admin
    tier: console
    version: main
